---
abstract: 'publish messages and subscribe to topics'
author:
  - 'Scott Beck <sabeck@cpan.org>'
build_requires:
  English: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.31
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.101980, CPAN::Meta::Converter version 2.101670'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Black-Board
requires:
  Moose: 0
  Moose::Autobox: 0
  Moose::Exporter: 0
  Moose::Util::TypeConstraints: 0
  MooseX::ClassAttribute: 0
  MooseX::Clone: 0
  MooseX::Declare: 0
  MooseX::Types: 0
  MooseX::Types::Moose: 0
  Scalar::Util: 0
resources:
  repository: git://github.com/bline/black-board.git
version: 0.0001
